version: '3.9'
services:
  contenedorcito:
      image: rusok/superproyectofx:1.1.0
      build: .
      ports:
        - 8000:8080
        - 8001:8081
      environment:
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_ENVIRONMENT=Development
      volumes:
        - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/